version: '3.7'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:3000"
    networks:
      - app-network
    command: npm run start:dev
    env_file:
      - .env

networks:
  app-network:
    external:
      name: app-network