version: '3.7'

services:
  users:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - users-network
      - app-network
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - "users-database"

  users-database:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - users-network

networks:
  users-network:
  app-network:
    external:
      name: app-network